version: "3.8"

services:
  folder2rss:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      RSS_SERVER_HOST: "0.0.0.0"
      RSS_SERVER_PORT: "8000"
      RSS_SERVER_DIRECTORY: "podcasts"
      RSS_SERVER_SUBFOLDER: "folder2rss"
    volumes:
      - "./podcasts:/app/podcasts:ro"
